//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTourDuLich.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public Destination()
        {
            this.Hotels = new HashSet<Hotel>();
            this.TourSites = new HashSet<TourSite>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
    
        public virtual ICollection<Hotel> Hotels { get; set; }
        public virtual ICollection<TourSite> TourSites { get; set; }
    }
}
