//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTourDuLich.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public string customer_id { get; set; }
        public string category_id { get; set; }
        public string tour_group_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PassengerCategory PassengerCategory { get; set; }
        public virtual TourGroup TourGroup { get; set; }
    }
}
