//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTourDuLich.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourCategory
    {
        public TourCategory()
        {
            this.Tours = new HashSet<Tour>();
            this.TourGroups = new HashSet<TourGroup>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Tour> Tours { get; set; }
        public virtual ICollection<TourGroup> TourGroups { get; set; }
    }
}
