//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTourDuLich.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourGroup
    {
        public TourGroup()
        {
            this.Passengers = new HashSet<Passenger>();
        }
    
        public string id { get; set; }
        public string tour_id { get; set; }
        public System.DateTime depart_date { get; set; }
        public System.DateTime return_date { get; set; }
    
        public virtual ICollection<Passenger> Passengers { get; set; }
        public virtual TourCategory TourCategory { get; set; }
    }
}
