//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Passengers = new HashSet<Passenger>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int gender { get; set; }
        public string nationality { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual ICollection<Passenger> Passengers { get; set; }
    }
}
