//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourGroupDetail
    {
        public string tour_id { get; set; }
        public string employee_id { get; set; }
        public string transport_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
