//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public Tour()
        {
            this.TourGroupDetails = new HashSet<TourGroupDetail>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string category_id { get; set; }
        public string tour_price_id { get; set; }
    
        public virtual TourCategory TourCategory { get; set; }
        public virtual TourPrice TourPrice { get; set; }
        public virtual ICollection<TourGroupDetail> TourGroupDetails { get; set; }
    }
}
